server.port=8082

eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka

spring.application.name=gateway
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true

springdoc.swagger-ui.urls[0].name=pagamentos
springdoc.swagger-ui.urls[0].url=/pagamentos-ms/v3/api-docs

springdoc.swagger-ui.urls[1].name=pedidos
springdoc.swagger-ui.urls[1].url=/pedidos-ms/v3/api-docs
